### ISSUE TITLE
Icon invisible on dark background

### ISSUE THREAD

**Issue by Golutazem** [benbuck/upshift#1]
When the background of the address bar is nearly black, the upshift icon is invisible.

**Comment by benbuck** [comment]
Hi @edakiri,

I think this should be fixed now, please let me know if you still have trouble seeing it.

Thanks,
Benbuck

**Comment by Golutazem** [comment]
Has it been updated on the Chrome store?  I uninstalled and selected install again.  I see a faint outline around the arrow, but it is still difficult to see.

**Comment by benbuck** [comment]
Hi @Golutazem,

I update the icon again today, it should have a bit more pronounced outline now. If that still doesn't work for you, please send me a screenshot.

Thanks,
Benbuck
