### ISSUE TITLE
Regularly replaces contents of address bar with address from a different window

### ISSUE THREAD

**Issue by DrStrangepork** [benbuck/upshift#3]
This has been happening for a while, just getting around to opening a ticket
In this example, I have https://www.ultimate-guitar.com/ open in another window

![Screen Shot 2022-08-16 at 12 53 54 PM](https://user-images.githubusercontent.com/7307373/184936487-fe4e7ef2-dd27-46c5-8f51-cd9dfc8ac275.png)

**Comment by benbuck** [comment]
Hi @DrStrangepork,

Thanks for reporting this problem. I haven't seen this myself. Do you know if there's any way I can reproduce it? Is there any pattern to when it happens for you?

Thanks,
Benbuck

**Comment by DrStrangepork** [comment]
I have not been able to determine when the pattern begins. The extension seems to recognize one window as the source of the URL, and the paths in Upshift in every other window will mirror whatever tab is active in that window. If that window is closed, Upshift goes completely blank for a while, then it just picks up a new window-tab as active. And using Upshift from any other window manipulates the source window-tab, not the tab of the active window that I am using the Upshift button with, even when the source window is minimized. Turning the extension off and on again does not change any of this behavior. This behavior does not cross profiles.

I have also noticed the service worker flapping, going Inactive sporadically.
<img width="406" alt="image" src="https://user-images.githubusercontent.com/7307373/215798164-fb11fac5-6d8f-4667-b47b-46bad099535b.png">

I use Upshift with Chrome and Brave. I keep Upshift and browsers at the most current version.
